name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.extract_tag.outputs.release_tag }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract release tag
      id: extract_tag
      run: echo "release_tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: |
        docker build -t fastqueue:${{ steps.extract_tag.outputs.release_tag }} .

    - name: Save Docker image
      run: docker save fastqueue:${{ steps.extract_tag.outputs.release_tag }} -o image.tar

    - name: Upload image artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: image.tar

  dockerhub-push:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download image artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-image
        path: .

    - name: Load Docker image
      run: docker load -i image.tar

    - name: Tag for Docker Hub
      run: docker tag fastqueue:${{ needs.build.outputs.release_tag }} ${{ secrets.DOCKERHUB_USERNAME }}/fastqueue:${{ needs.build.outputs.release_tag }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastqueue:${{ needs.build.outputs.release_tag }}

  ghcr-push:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download image artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-image
        path: .

    - name: Load Docker image
      run: docker load -i image.tar

    - name: Tag for GHCR
      run: docker tag fastqueue:${{ needs.build.outputs.release_tag }} ghcr.io/${{ github.repository_owner }}/fastqueue:${{ needs.build.outputs.release_tag }}

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to GHCR
      run: docker push ghcr.io/${{ github.repository_owner }}/fastqueue:${{ needs.build.outputs.release_tag }}